# Generated by Django 4.2.9 on 2024-10-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="An", max_length=50, verbose_name="логин"),
            preserve_default=False,
        ),
    ]
